const menu = [
    {
      id: 1,
      title: 'buttermilk pancakes',
      category: 'breakfast',
      price: 15.99,
      img: 'https://saramellas.com/wp-content/uploads/2020/08/IMG_9662.jpg',
      desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    },
    {
      id: 2,
      title: 'diner double',
      category: 'lunch',
      price: 13.99,
      img: 'https://th.bing.com/th/id/R.c9d2e558c46c5ec22c4d6fcba20215d3?rik=Lt7rYI6Jiz954g&pid=ImgRaw&r=0',
      desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
    },
    {
      id: 3,
      title: 'godzilla milkshake',
      category: 'shakes',
      price: 6.99,
      img: 'https://react-project-5-menu.netlify.app/images/item-3.jpeg',
      desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
    },
    {
      id: 4,
      title: 'country delight',
      category: 'breakfast',
      price: 20.99,
      img: 'https://i.pinimg.com/originals/a3/de/48/a3de48a5e19275785435abacbbc385a7.jpg',
      desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
    },
    {
      id: 5,
      title: 'egg attack',
      category: 'lunch',
      price: 22.99,
      img: 'https://th.bing.com/th/id/R.401139426381a9ef3755bd506cfe3da5?rik=vdXW4b47%2bK1PfA&pid=ImgRaw&r=0',
      desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
    },
    {
      id: 6,
      title: 'oreo dream',
      category: 'shakes',
      price: 18.99,
      img: 'https://th.bing.com/th/id/OIP.Y5mWdf6ke0t_Nh3Tl5yITwHaFj?pid=ImgDet&rs=1',
      desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
    },
    {
      id: 7,
      title: 'bacon overflow',
      category: 'breakfast',
      price: 8.99,
      img: 'https://th.bing.com/th/id/OIP.C19J23AwC7fU6VCDBu2fuwHaEK?pid=ImgDet&rs=1',
      desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
    },
    {
      id: 8,
      title: 'american classic',
      category: 'lunch',
      price: 12.99,
      img: 'https://th.bing.com/th/id/R.b5f9222e8bab7affb9211454efa22c0f?rik=0Az9w%2bmypTDWwg&pid=ImgRaw&r=0',
      desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
    },
    {
      id: 9,
      title: 'quarantine buddy',
      category: 'shakes',
      price: 16.99,
      img: 'https://th.bing.com/th/id/OIP.6p-Xn69h1y7zl5tWKBIRegHaE5?pid=ImgDet&rs=1',
      desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
    },
  ];
  export default menu;